### ISSUE TITLE
@hook('upgrade-charm) not registering

### ISSUE THREAD

**Issue by chris-sanders** [juju-solutions/charms.reactive#103]
I've been fighting with @hook for 'upgrade-charm' and can not get it to work. I've hooked on config-change and reduced my function to a simple print statement. 
```python
@hook('upgrade-charm')
def test_function():
  print("Upgrade triggered")
```
Eventually I hacked a state into the upgrade-charm hook template and was able to trigger by catching that state with the @when decorator instead. 
```python
@when('upgrade.charm')
def test_function():
  print("Upgrade triggered")
```

I'm triggering this from a debug-hook session and calling the upgrade-charm hook directly. After getting this to work via the @when and a custom state, and getting @hook to work with config-changed I'm out of ideas. 

This is reported as version 0.4.5 when I trigger the charm upgrade. Is there a better way to see the version of charms.reactive if I weren't working with charm upgrade I don't know where I would have seen the version number.

**Comment by jamesbeedy** [comment]
@chris-sanders are you using hook imported from charms.reactive?

**Comment by chris-sanders** [comment]
Yes, 
```python
from charms.reactive import hook, when, when_any, when_not, set_state, remove_state
```

And I was able to hook on config-changed with out issue.

**Comment by chris-sanders** [comment]
I should also say, I get no errors at all when running the hook. I did initially forget to import the hook but that does produce an error when you run the hook from the debug terminal.

**Comment by stub42** [comment]
upgrade-charm hooks are working fine for me. I think there is something odd in your generated charm, for example hooks/upgrade-charm missing the executable bit. People will need an example charm that fails to investigate further.

**Comment by chris-sanders** [comment]
Fair enough, maybe I've made a charm mistake. I'll see if I can roll back the charm I was working on to replicate and provide a link.

**Comment by chris-sanders** [comment]
Ok, I just rolled back an I can't replicate what I was seeing before. I'm not sure why but it's triggering on @hook when I couldn't get it to do that before. I'll close this issue.
