### ISSUE TITLE
Doc release process is deprecated and broken

### ISSUE THREAD

**Issue by johnsca** [juju-solutions/charms.reactive#104]
The upload_sphinx process for hosting docs with pythonhosted.org has been deprecated and now seems to be broken.  I've removed it for the time being from the release process, but this means that the docs will continue to fall out of date.

We need to replace the docs release process with [RTD](https://readthedocs.org/)

**Comment by johnsca** [comment]
Docs can still be manually uploaded to PythonHosted.org, and it looks like the built-in `upload_docs` target works, but it reports that it, and presumably PythonHosted.org, is deprecated.

I added the reactive docs to RTD at https://charmsreactive.readthedocs.io/en/latest/ and it will build automatically from master.  We just need to figure out a way to transition over.  Ideally, I'd like PythonHosted.org to redirect, but I can't find a reasonable way to do that.

**Comment by galgalesh** [comment]
This seems a reasonable way: https://blog.gocept.com/2017/05/27/move-documentation-from-pythonhosted-org-to-readthedocs-io/

> This requires a directory – for this example I name it redir – containing a file named index.html with the following content:

```
<html>
<head>
 <title>zodb.py3migrate</title>
 <meta http-equiv="refresh"
       content="0; url=http://zodbpy3migrate.rtfd.io" />
</head>
<body>
  <p>
    <a href="http://zodbpy3migrate.rtfd.io">
      Redirect to zodbpy3migrate.rtfd.io
    </a>
  </p>
</body>
</html>
```

**Comment by galgalesh** [comment]
The issue I see is that readthedocs shows the docs of the `master` branch by default. I think two versions should be available: `stable` and `devel` (mirroring the Juju docs terminology). Is this possible with readthedocs?

**Comment by galgalesh** [comment]
PS: can you make me owner on readthedocs? `galgalesh`.

**Comment by johnsca** [comment]
+1 on having the two versions.  You are now a maintainer on RTD

**Comment by johnsca** [comment]
I looked in to the redirect file approach at one point and for some reason recall thinking it wouldn't work.  But +1 if it will.

**Comment by galgalesh** [comment]
Ok, I found the issue. Readthedocs has some magic algorithm to determine what the latest "stable" release is. It seems that our `2.0` branch is confusing that algorithm (2.0 > 0.5.3): readthedocs thinks our 2.0 branch is the latest "stable" release.

I renamed our 2.0 branch to `2.0a1` and now the algorithm does the correct thing: `stable` is the latest tagged release (0.5.3 now) and `latest` is the `master` branch.

![image](https://user-images.githubusercontent.com/1492981/31246538-fad1f59c-aa0d-11e7-956e-0491c23d97f8.png)

![image](https://user-images.githubusercontent.com/1492981/31246563-0c5ab394-aa0e-11e7-9852-8ef788c86746.png)

**Comment by galgalesh** [comment]
It seems we're too late to put redirect docs on pythonhosted. Uploading the docs now fails with `Upload failed (410): Gone`.

We do have a "destroy docs" button.

![image](https://user-images.githubusercontent.com/1492981/31272048-e18d79ae-aa89-11e7-88bd-ec9f45e69004.png)

I propose we use that. It's better for users to get a 404 than to see outdated docs. Especially since the pythonhosted docs is still the primary result in Google.

![image](https://user-images.githubusercontent.com/1492981/31272100-08ba9f84-aa8a-11e7-968b-c933c6470c69.png)

**Comment by galgalesh** [comment]
Juju docs are updated and pythonhosted docs are removed. Now Google just needs to refresh its index and the pain is finally over!
