### ISSUE TITLE
Style Guide

### ISSUE THREAD

**Issue by AdamIsrael** [juju-solutions/charms.reactive#114]
It'd be useful to create a style guide for things like British vs. American spellings, one or two spaces after a period, etc.

It's a common enough problem that there may be a lint-style toolkit to automatically check documentation and that would be really great to incorporate here.

**Comment by galgalesh** [comment]
The Juju docs style guide might be a good start for this, but I honestly think this would add much value. Feel free to reopen if you think this is important or if you want to create one.
