### ISSUE TITLE
Enable @hook and @when (et al.) to be used together

### ISSUE THREAD

**Issue by johnsca** [juju-solutions/charms.reactive#12]
For consistent and correct ordering of handlers, there is a "hook phase" in which all `@hook` handlers are triggered, _before_ any `@when` handlers are triggered.  However, this leads to the surprising result that you cannot combine `@hook` with any other decorator, even though it is often useful and intuitive to do so.

If possible, we should support this use-case, even if it can sometimes lead to odd corner-case behavior, as long as the behavior is consistent and well-documented.

**Comment by stub42** [comment]
This would allow ordering of @hook handlers when multiple layers need to handle the same event.

```python
@hook('install', 'config-changed')
def layer_install():
    '''Add user defined package sources per charmhelpers standard'''
    fetch.configure_sources()
    fetch.apt_update()
    set_state('apt.updated')

@hook('install')
@when('apt.updated')
def install():
    fetch.apt_install('mydeb')
```
