### ISSUE TITLE
Subordinate charm downgrades charms.reactive breaking primary

### ISSUE THREAD

**Issue by stub42** [juju-solutions/charms.reactive#135]
A PostgreSQL charm is installed happily, using the default of no venv, and has charms.reactive 0.5 installed into /usr/local.

A canonical-livepatch subordinate is installed, also not using a venv, and the charms.reactive in /usr/local is downgraded to 0.4.7. This breaks the primary charm:

```
unit-canonical-livepatch-5.log:2017-10-23 20:43:39 DEBUG install Processing ./wheelhouse/charms.reactive-0.4.7.tar.gz
unit-canonical-livepatch-5.log:2017-10-23 20:43:39 DEBUG install Requirement already up-to-date: pyaml in /usr/local/lib/python3.5/dist-packages (from charms.reactive==0.4.7)
unit-canonical-livepatch-5.log:2017-10-23 20:43:39 DEBUG install Building wheels for collected packages: pip, six, netaddr, charmhelpers, MarkupSafe, charms.reactive
unit-canonical-livepatch-5.log:2017-10-23 20:43:42 DEBUG install   Running setup.py bdist_wheel for charms.reactive: started
unit-canonical-livepatch-5.log:2017-10-23 20:43:42 DEBUG install   Running setup.py bdist_wheel for charms.reactive: finished with status 'done'
unit-canonical-livepatch-5.log:2017-10-23 20:43:42 DEBUG install Successfully built pip six netaddr charmhelpers MarkupSafe charms.reactive
unit-canonical-livepatch-5.log:2017-10-23 20:43:42 DEBUG install Installing collected packages: pip, six, netaddr, charmhelpers, MarkupSafe, charms.reactive
unit-canonical-livepatch-5.log:2017-10-23 20:43:43 DEBUG install   Found existing installation: charms.reactive 0.5.0
unit-canonical-livepatch-5.log:2017-10-23 20:43:43 DEBUG install     Uninstalling charms.reactive-0.5.0:
unit-canonical-livepatch-5.log:2017-10-23 20:43:43 DEBUG install       Successfully uninstalled charms.reactive-0.5.0
unit-canonical-livepatch-5.log:2017-10-23 20:43:43 DEBUG install Successfully installed MarkupSafe-1.0 charmhelpers-0.18.0 charms.reactive-0.4.7 netaddr-0.7.19 pip-8.1.2 six-1.10.0
```

This issue will affect all deployments with primaries and subordinates mixing charms.reactive 0.5 and pre-0.5, and at least one charm not using the virtual env option. If any of the charms depend on the 0.5 API, then the deployment will break. It may not break immediately, depending on which order the install hooks run, but will certainly break when upgrade-charm's are run later.

**Comment by johnsca** [comment]
Historically, it's always been up to the subordinate charm author to ensure that their charm doesn't conflict with the principal.  The `use_venv` option was added to make that easier, but due to concerns about ensuring that the venv was activated properly during debug sessions or in bash charms (i.e., whenever the `charms.reactive` CLI is used), it wasn't made the default.  I think we could probably come up with a shim `charms.reactive` CLI that checks for the current hook environment and activates the proper venv, if available.  If we can do that, I'm +1 for making `use_venv` the default.  In the meantime, we can certainly add something to layer-basic (where the `use_venv` option is handled) to detect if it's not using `use_venv` (perhaps only for subordinates at first?) during build time and warn the charm author that it's a problem.

**Comment by stub42** [comment]
I agree that making `use_venv` the default is the way forward. There doesn't seem to be a way to control pip the way we need, and we don't want to rewrite pip.

The issue here is that a person updates their reactive charm, and it breaks during deployment. They are being victimized by subordinate charms that are unchanged.

If we can get a build time warning, that would be good and mostly address the immediate issue.

I do wonder if we should just make it the default now, since we are already starting to see incompatible API changes. We have concerns about problems people might have, but it would solve we know people are having.

The `charms.reactive` cli command could certainly automatically use the correct interpreter using a shim or wrapper.

debug sessions is more of a problem. While users running 'hooks/config-changed' could work fine using a similar or the same mechanism to `charms.reactive`, users running 'pdb3 hooks/config-changed' will have no such luck.

**Comment by ajkavanagh** [comment]
@stub42 I had this exact problem with 2 reactive charms, one principle and one subordinate.  I was making changes to a shared library on one of them and it broke the other in interesting ways, and it was a while before I worked out it was pollution from the other charm.  I use the 'use_venv' as a default now.  I'm a definite +1 to having 'use_venv' as the default.

**Comment by hloeung** [comment]
Another +1 for me to make 'use_venv' the default.

**Comment by hloeung** [comment]
If/when use_venv becomes the default, would we also need to make include_system_packages the default as well?

**Comment by stub42** [comment]
include_system_packages should default to true for backwards compatibility.
