### ISSUE TITLE
Removing state should not reschedule all handlers

### ISSUE THREAD

**Issue by stub42** [juju-solutions/charms.reactive#15]
From the docs: "removing a state causes the queue to be immediately re-evaluated. This ensures that a handler is never invoked when the state is no longer active"

Rather than tossing out the current queue of handlers and re-evaluating it completely, it would be better if the queue was scanned and handlers that should no longer trigger removed.

```python
def add_source(source, key):
    fetch.add_source(source, key)
    reactive.set_state('apt.needs_update')

@reactive.when('apt.needs_update')
def update():
    fetch.apt_update()
    reactive.remove_state('apt.needs_update')
```

In the above example, multiple handlers in the current iteration can call add_source. The slow update handler will not be called until after the current iteration of handlers has been exhausted and a new generation scheduled. Unless one of the handlers calls reactive.remove_state, causing the queue to be immediately reevaluated and this optimization lost.

Or is what I suggest already how it is implemented, or causes some other problem?

**Comment by johnsca** [comment]
That bit of doc is misleading, and the API docs for [dispatch](https://pythonhosted.org/charms.reactive/charms.reactive.bus.html#charms.reactive.bus.dispatch) are more accurate.  What actually happens is that the remaining set of handlers that matched and have not yet been triggered are re-tested, and any that no longer pass are filtered out.  Your example should work as you expect.  I'll update the main docs to reflect this.
