### ISSUE TITLE
Update juju docs for interface layers to endpoint pattern

### ISSUE THREAD

**Issue by szeestraten** [juju-solutions/charms.reactive#150]
The juju docs for [developing interface layers](https://github.com/juju/docs/blob/660e3199cb33ef0958277b24298effddb12225bb/src/en/developer-layers-interfaces.md) needs to be updated for the new endpoint pattern.

**Comment by galgalesh** [comment]
Yes, we have a PR open that's waiting to be merged: https://github.com/juju/docs/pull/2207

**Comment by galgalesh** [comment]
Merged and published: https://jujucharms.com/docs/2.3/developer-layers-interfaces
