### ISSUE TITLE
joined flag only removed in the hook after the relation-broken hook

### ISSUE THREAD

**Issue by galgalesh** [juju-solutions/charms.reactive#151]
The docs say the following

> the `joined` flag will be automatically cleared when there are no remote units remaining on any relation, but neither of the other flags will be automatically cleared.

I read this as "the `joined` flag will be removed **when the last unit of the last relationship is `departed`**". So for an endpoint with one relation and one remote unit, the `joined` flag will be removed at the same time that the `departed` flag is set.

This is however not the case: the `joined` flag is only removed when during the hook _after_ the  `relation-broken` hook because that is the first time when Juju says that there are no relations/units connected anymore.

Look at this output. The desired behavior is that the `joined` flag is removed in the first `departed` hook, not in the `update-status` hook.

``` bash
# Departed hook
2018-01-18 13:16:30 INFO juju-log kubernetes-request:94: Reactive main running for hook kubernetes-request-relation-departed
2018-01-18 13:16:31 INFO juju-log kubernetes-request:94: Invoking reactive handler: reactive/kubernetes-resource.py:11:print_flags
2018-01-18 13:16:31 INFO juju-log kubernetes-request:94: [
  'endpoint.kubernetes-request.changed', 
  'endpoint.kubernetes-request.changed.egress-subnets', 
  'endpoint.kubernetes-request.changed.ingress-address', 
  'endpoint.kubernetes-request.changed.private-address', 
  'endpoint.kubernetes-request.departed', 
  'endpoint.kubernetes-request.joined', 
  'kubernetes.connected']

# Broken hook
2018-01-18 13:16:32 INFO juju-log kubernetes-request:94: Reactive main running for hook kubernetes-request-relation-broken
2018-01-18 13:16:32 INFO juju-log kubernetes-request:94: Invoking reactive handler: reactive/kubernetes-resource.py:11:print_flags
2018-01-18 13:16:32 INFO juju-log kubernetes-request:94: [
  'endpoint.kubernetes-request.changed', 
  'endpoint.kubernetes-request.changed.egress-subnets', 
  'endpoint.kubernetes-request.changed.ingress-address', 
  'endpoint.kubernetes-request.changed.private-address', 
  'endpoint.kubernetes-request.departed', 
  'endpoint.kubernetes-request.joined', 
  'kubernetes.connected']

# Update status hook
2018-01-18 13:21:27 INFO juju-log Reactive main running for hook update-status
2018-01-18 13:21:27 INFO juju-log Invoking reactive handler: reactive/kubernetes-resource.py:16:k8s_resource_install
2018-01-18 13:21:27 INFO juju-log NO DEPLOYER RELATION
2018-01-18 13:21:27 INFO juju-log Invoking reactive handler: reactive/kubernetes-resource.py:11:print_flags
2018-01-18 13:21:28 INFO juju-log [
  'endpoint.kubernetes-request.changed',
  'endpoint.kubernetes-request.changed.egress-subnets',
  'endpoint.kubernetes-request.changed.ingress-address',
  'endpoint.kubernetes-request.changed.private-address',
  'endpoint.kubernetes-request.departed']
```

This behavior requires a developer to know the intricacies of when Juju stops saying there is a relationship.

I propose we remove the `joined` flag, during the `departed` hook of the last unit of the last relationship.

1. It's more intuitive,
2. it's how it's explained in the docs,
3. and the current behavior serves no purpose, afaik.

What do you think, @johnsca ?

**Comment by ajkavanagh** [comment]
It's definitely a strange beast, Juju.  The departed hook is run for a relation that is 'departing'; so technically, it's still there, but in the process of "going away".  After the hook has run, *then* (whilst the charm code is not running), the relation really disappears.  So, for the *joined* flag, it depends on what it's *supposed* to mean:

1. If *joined* is set whilst a relation exists, then the current behaviour is correct.
2. If *joined* is set whilst the relation *meaningfully* exists, then the current behaviour is incorrect.  By *meaningfully*, I'm wondering if whether a dying relationship is still useful.

It also depends on how the *joined* flag is use in code?  There's also something complex in there (which I've not fully thought through) about how/if the joined flag can be used to do clean-up.  Hmm.

**Comment by johnsca** [comment]
The flag should probably be driven by `len(self.all_units) > 0` rather than `len(self.relations) > 0` but even so it won't be cleared during the `-departed` hook since the unit is still there, as @ajkavanagh said.

**Comment by galgalesh** [comment]
I think the unit still being there doesn't really have meaning in the endpoints pattern; is an endpoint different when the unit is still there but departed vs when it's gone? :thinking: 

Treating these two states as different makes things more complicated, so we need a good reason to keep it, imo. Are there any use-cases where this differentiation would be useful? :thinking:

**Comment by xannz** [comment]
I ran into this scenario. I wanted to set a flag when a remote unit joined and remove it again when no units are available. So I tried the following:
```
@when_any('endpoint.{endpoint_name}.joined')
def request_joined(self):
    set_flag(self.expand_name('available'))

@when_any('endpoint.{endpoint_name}.departed')
def request_joined(self):
    clear_flag(self.expand_name('available'))
    clear_flag(self.expand_name('departed'))
```
This gave the unexpected result that the `available` flag was set after the removal of the relation. The broken hook is run after departed and so the flag is set again.

**Comment by johnsca** [comment]
@xannz I assume the duplicate function name is a copy-paste error?  But the `@when_any('endpoint.{endpoint_name}.departed')` bit is also fundamentally incorrect, since that flag will be set when *any* unit is departing.  The correct logic would be:

```python
@when_any('endpoint.{endpoint_name}.joined')
def request_joined(self):
    set_flag(self.expand_name('available'))

@when_none('endpoint.{endpoint_name}.joined')
def request_broken(self):
    clear_flag(self.expand_name('available'))
    clear_flag(self.expand_name('departed'))
```

In that case, the flags should get cleaned up as expected during the `-broken` hook, which seems like the most reasonable timing.  (Well, it would be `-broken` except for the issue that it currently checks for relation IDs instead of units, which could cause a delay.  Even so, it would go to the expected state during the next hook to fire.)

That said, I'm not 100% committed to the behavior of waiting until the last unit is actually truly gone, but I'm still leaning that way since it seems more consistent with the charm's view of the world.

**Comment by xannz** [comment]
@johnsca Thanks for clarifying where I went wrong. I ended up setting a flag whenever a relation departed or when a changed flag is set.

```python
@when_any('endpoint.{endpoint_name}.joined')
def upstream_joined(self):
    set_flag(self.expand_name('available'))

@when_not('endpoint.{endpoint_name}.joined')
def upstream_broken(self):
    clear_flag(self.expand_name('available'))

@when_any('endpoint.{endpoint_name}.changed.nginx_config',
          'endpoint.{endpoint_name}.departed')
def upstream_changed(self):
    set_flag(self.expand_name('new-upstream'))
    clear_flag(self.expand_name('changed.nginx_config'))
    clear_flag(self.expand_name('departed'))
```

**Comment by johnsca** [comment]
@xannz Yes, that looks like a good pattern.

The only way I could see removing the need for also checking for `.departed` in addition to `.changed` would be to have the units collections implicitly filter out the unit that is currently departing (and presumably have some other way of accessing that unit, though in general I feel like something that is only available for a single hook context goes against what I think of as best practices). I think that might actually fit better with everyone's expectations and thus be easier to understand, and I believe it would address the original ask for this issue.  @galgalesh @ajkavanagh?  Something like:

```python
class MyEndpoint(Endpoint):
    @when('endpoint.{endpoint_name}.joined')
    def check_client_list(self):
        if data_changed(self.expand_name('clients'), self.clients()):
            set_flag(self.expand_name('changed.clients'))

    def clients(self):
        return [unit.received['private-address'] for unit in self.all_units]

    def departing_client(self):
        return self.departing_unit.received['private-address']
```

**Comment by galgalesh** [comment]
Having certain values available only in certain hooks seems like a reactive anti-pattern to me. It shouldn't matter in which hook a handler runs. Could we maybe cache this info until the departed flag is actually cleared? That would make most sense to me, then it doesn't matter during which hook it runs.

**Comment by johnsca** [comment]
I'm not keen on having the list magically tied to the flag, but having a mutable collection that caches the information about the departed units seems like a good idea.  We would probably want to cache all of the relation data as well, since it's not accessible after from Juju, though that would mean keeping a cache of all relation data for all units.

**Comment by galgalesh** [comment]
> I'm not keen on having the list magically tied to the flag

Agreed, although I'd argue that it's better to be magically tied to a flag than to have it magically tied to a hook, but ideally, nothing gets removed magically.

>  but having a mutable collection that caches the information about the departed units seems like a good idea. We would probably want to cache all of the relation data as well, since it's not accessible after from Juju, though that would mean keeping a cache of all relation data for all units.

Ideally we'd have two collections: unit that are still joined and units that are departed.

# On-topic

But to go back ontopic to the original issue, I'd still like to make it so that the `joined` flag gets removed when the last unit is `departed`. It makes a lot of sense to me semantically; joined and departed are two opposites; when everything is departed, nothing is joined. I think the current behavior only makes sense when you know the intricacies of how Juju relationships work exactly, and not many charmers do.

It might be useful to have a flag indicate when the relationship is really gone; but I think it's better to give that flag a different name. However I'm not sure if that's useful, I can't think of any use-cases that need this distinction.

**Comment by johnsca** [comment]
Ok, I'm in full agreement.  We add a list of departed units, and as soon as a unit is departed, it's no longer joined.  And as soon as there are no joined units, the joined flag is removed.
