### ISSUE TITLE
Improvement endpoint docs

### ISSUE THREAD

**Issue by xannz** [juju-solutions/charms.reactive#152]
@galgalesh It would be nice if the docs concerning the new endpoint implementation could highlight some major changes that affect the behaviour of flags. 

For example:

> These are mainly intended to be used by the interface layer itself, but can be documented as part of the official API that the interface layer exposes. Additionally, the joined flag will be automatically cleared when there are no remote units remaining on any relation, but neither of the other flags will be automatically cleared. 

This is a big difference and is easy to miss in the wall of text. A notification box or some kind of warning would be helpful.

**Comment by johnsca** [comment]
I also noticed that the unit view classes (e.g., `CombinedUnitsView`, `RelatedUnit`, `UnitDataView`, etc) are not being included in the docs, even though they're in the index (see https://charmsreactive.readthedocs.io/en/latest/charms.reactive.relations.html#charms.reactive.endpoints.Endpoint)
