### ISSUE TITLE
Docs fail to build

### ISSUE THREAD

**Issue by galgalesh** [juju-solutions/charms.reactive#155]
Docs are currently failing: https://readthedocs.org/projects/charmsreactive/builds/6780320/

I can't seem to reproduce this on my local machine.

**Comment by ajkavanagh** [comment]
Looks like it's a docutils 0.13.1 problem.  We could pin perhaps  to 0.12?

See: https://github.com/sphinx-doc/sphinx/issues/3951

**Comment by johnsca** [comment]
Current version is 0.14 which still seems to have the issue.
