### ISSUE TITLE
set_flag's value parameter is undocumented

### ISSUE THREAD

**Issue by stub42** [juju-solutions/charms.reactive#158]
The set_flag docstring does not mention the value parameter and it does not end up in generated docs. I think this is the only mechanism for a user to link an endpoint to a state, so I think it needs to be blessed. Either that or the endpoint.{name} flags must be part of the interface's public API.

**Comment by johnsca** [comment]
The value param is more of a hold-over from the `RelationBase` approach and my inclination is deprecate it in favor of using the flag name.  Thoughts?

**Comment by stub42** [comment]
In order to transition existing RelationBase interfaces to Endpoints, the new Endpoint implementation needs to work as expected with existing handlers such as:

```
@when('db.connected')
def handler(db):
    db.do_stuff()
```

I think this means my Endpoint needs to do:

```
class MyDB(Endpoint):
    @when('endpoint.{endpoint_name}.joined')
    def joined(self):
        set_state(self.expand_name('{endpoint_name}.connected'), self)
```

(and at some future point, drop compatibility with the old implementation)

**Comment by stub42** [comment]
I see, thanks. Lets close this, as I think this covers all real world cases.
