### ISSUE TITLE
Add @when_any decorator

### ISSUE THREAD

**Issue by battlemidget** [juju-solutions/charms.reactive#16]
Right now `@when('service.available', 'anotherservice.available')` is performed with `AND`, it would be nice to have a `@when_any` to perform `OR` checks for states. This was briefly discussed on IRC today.

**Comment by stub42** [comment]
This would also be possible:

@when(State('service.avaliable') or (State('anotherservice.available') and not State('whatever')))

I don't have use cases for this yet, but if others need OR checks maybe it is worth going the whole hog and allowing arbitrary boolean operations like above. Or maybe when_any is the last that is needed and the most readable solution.

**Comment by johnsca** [comment]
I'd really like to avoid complex logic in the decorators.  Also, it doesn't work well with Bash / external handlers.

I actually started implementing a `@when_any` decorator and then realized an issue with it: it would make the arguments that get passed into the handler ambiguous.  There was some discussion at one point of passing in a single "context" variable that would  have the relation instances as attributes, which would resolve this, but then it becomes less clear at a glance as to what relations are available within the handler.

**Comment by stub42** [comment]
@johnsca Couldn't the arguments to the handler with ```@when_any``` be the same as ```@when```, except with None as the value for states that are not set?

I'd like to know if we will get ```@when_any``` or not, as it significantly changes the design of a Config layer I'd like to put together

```python
@when_any('config.changed.foo', 'config.initial')
def first_hook_or_foo_changed(): pass
```

vs.

```python
@when('config.changed.foo')
@when_not('config.initial')
def foo_changed_but_not_first_hook: pass
```
