### ISSUE TITLE
Consider exposing or dropping Relation._flush_data

### ISSUE THREAD

**Issue by stub42** [juju-solutions/charms.reactive#160]
If I use Relation.to_publish or Relation.to_publish_raw, relation-set is not called immediately. This means that code using the Relation object sees different relation data than code using relation-get.

Consider making the Relation._flush_data method public, so I can synchronize my Relation with the actual relation data.

Consider flushing after every write to Relation.to_publish. Juju already rolls back relation changes on hook failure, so deferring the flush until the end is just an optimization.

**Comment by galgalesh** [comment]
> This means that code using the Relation object sees different relation data than code using relation-get.

I thought `relation-get` only showed the relation data that the other side published?

> Consider making the Relation._flush_data method public, so I can synchronize my Relation with the actual relation data.

I think this is the best option so most charms still use the optimization.

**Comment by stub42** [comment]
@galgalesh You can also use relation-get to inspect your own published data. relation-get -r relid - $LOCAL_UNIT.

**Comment by johnsca** [comment]
I think the purpose of `_flush_data` was the "difficulty" of hooking in to the `__setitem__` of the `UnitDataView` but I think adding a callback wouldn't be terrible and having `relation_set` called immediately is preferable.

**Comment by stub42** [comment]
Closed in favor of using Endpoint
