### ISSUE TITLE
@sets decorator?

### ISSUE THREAD

**Issue by stub42** [juju-solutions/charms.reactive#17]
Rather than adhoc text in the docstring, perhaps documenting what states a handler sets or removes is better done with a decorator?

```python
@when('trigger')
@sets('valid')
def doit():
    toggle_state('valid', random() > 0.5)
```

Not only would this encourage consistent documentation, it could log warnings if undeclared state changes where made.

**Comment by johnsca** [comment]
Unfortunately, this doesn't work with external handlers, but it would work for interface layers because they are required to be in Python currently.

**Comment by stub42** [comment]
I was thinking the big value of this information would be that we could diagram complex charms, at which point I realized we should not design the decorators until we know what such a diagram should look like.
