### ISSUE TITLE
register_trigger does not work with deploy-time configuration

### ISSUE THREAD

**Issue by AdamIsrael** [juju-solutions/charms.reactive#192]
I've run into a use-case where register_trigger does not work. If a charm's configuration is set at the time of deployment, the 'config.changed' flag is processed but registered triggers are not. I first observed this behaviour when deploying via python-libjuju, and was able to recreate it when deploying the charm via the CLI.

To test, I created a layer called 'test-config-changed', and in [reactive/test-config-changed.py](https://gist.github.com/AdamIsrael/3747bb58163ed16c2ac12134ecbafca5) included the following:

```python
register_trigger(when='config.changed',
                 set_flag='trigger.config')

@when('config.changed')
def log_config_changed():
    cfg = config()
    log("#### config-changed state handled: {}".format(cfg))

@when('trigger.config')
def trigger_config_changed():
    cfg = config()
    log("#### trigger_config_changed called: {}".format(cfg))
```

To test, I deploy the charm and specify a config value, watching `juju debug-log` to verify behavior:
```bash
juju deploy ~/charms/builds/test-config-changed --config string-option="deploy"
```
With the above, I see that the function handling the 'config.changed' flag is called but 'trigger.config' is not.

If I set the config post-deploy...
```bash
juju config test-config-changed/0 string-option="config"
```
... the log shows both 'config.changed' and 'trigger.config' being called.

My expectation is that, in either case, registered triggers should work the same regardless of if the criteria is met during the initial deployment or afterward.

**Comment by AdamIsrael** [comment]
As a workaround, I've used when_any to catch both the original and triggered flag. I originally tried using a trigger for this because I ran into an edge case where config.changed was cleared before my handler ran.

```python
@when_any('config.changed', 'trigger.config')
def trigger_config_changed():
    cfg = config()
    log("#### trigger_config_changed called: {}".format(cfg))
```

**Comment by johnsca** [comment]
This is actually an issue with [`layer:basic`](https://github.com/juju-solutions/layer-basic) because it calls `init_config_states` before [discover](https://charmsreactive.readthedocs.io/en/latest/dispatch.html).  I'm going to move this issue there.
