### ISSUE TITLE
Flags now reset on upgrade-charm?

### ISSUE THREAD

**Issue by hloeung** [juju-solutions/charms.reactive#221]
Hi,

Deploying the content-cache charm. On upgrade-charm, it seems all the content_cache.* flags are removed? See:

https://pastebin.ubuntu.com/p/hjWGdtz6fC/

**Comment by hloeung** [comment]
FYI, the charm clears some, but not all, in particular 'content_cache.nginx.installed'.

https://git.launchpad.net/~content-cache-charmers/content-cache-charm/tree/reactive/content_cache.py#n27

**Comment by hloeung** [comment]
Even removed all the clear_flag() calls in the charm's upgrade_charm() and confirmed that those flags are gone:

https://pastebin.ubuntu.com/p/xfZfrCS3Fs/

**Comment by stub42** [comment]
Feels like the sqlite database containing charm state got destroyed. Did it happen to get packaged in the built charm? That would do it.

**Comment by hloeung** [comment]
Ah, that's exactly what it is. Didn't run 'make clean' and .unit-state.db was still around.
