### ISSUE TITLE
broken link in README.md

### ISSUE THREAD

**Issue by jugmac00** [juju-solutions/charms.reactive#247]
In the usage section there is a link to https://jujucharms.com/docs/stable/authors-charm-building which does not work anymore.

Is the referenced document available somewhere? We have to use reactive charms for some reasons, and we need to get our team up to speed with reactive charms.

**Comment by ajkavanagh** [comment]
`charms.reactive` is deprecated as the new framework is the Ops framework.  https://charmsreactive.readthedocs.io/en/latest/index.html might be useful as backgrounder info for getting up to speed with reactive charms.  Also https://discourse.charmhub.io/t/getting-started-with-charm-development/1118 may be useful.

I guess we ought to fix the link in the README though.
