### ISSUE TITLE
Python equivalent for RelationBase.set_remote loses the value parameter

### ISSUE THREAD

**Issue by stub42** [juju-solutions/charms.reactive#29]
In the docs, RelationBase.set_remote has the signature `set_remote(key=None, value=None, data=None, scope=None, **kwdata)`. However, in the equivalent Python the value parameter is lost.

**Comment by johnsca** [comment]
I'm not sure what you mean.  The docs are generated from the code, so they should always be in sync.  And the code seems to have the correct signature:

https://github.com/juju-solutions/charms.reactive/blob/master/charms/reactive/relations.py#L286

**Comment by stub42** [comment]
There is example code in the docstring. Fix is in b351a3451861a01fdbd559bc2dc94fede7bf23df

**Comment by johnsca** [comment]
Ah, thanks!
