### ISSUE TITLE
Flush unitdata after every handler?

### ISSUE THREAD

**Issue by johnsca** [juju-solutions/charms.reactive#38]
I've noticed during developing that if any handler fails, none of the unitdata gets flushed.  This means that on subsequent runs, states are reset to what they were at the start of the hook and even handlers that completed successfully are re-run.

I think we should flush after every successful handler to ensure that successful handlers are not re-run.  (Also note that everything is flushed before external handlers are run to ensure that they see the proper state.)

**Comment by stub42** [comment]
I was thinking this was a required feature. 'juju upgrade-charm --force'
followed by a 'juju resolved --retry' retries the entire hook again, with
your modified code paths. If you have an error state, you generally need to
somehow trigger different code paths to run. With the proposed change, if
an earlier handler failed to set state correctly that caused a later
handler to fail your unit is screwed.

Perhaps external handlers need to get their behaviour changed to match,
being passed a temporary copy of the unitdata and modifications they make
merged back if they return successfully.


-- 
Stuart Bishop <stuart@stuartbishop.net>
http://www.stuartbishop.net/

**Comment by galgalesh** [comment]
This might be a good idea. It will make resolving errors a lot easier. If state is lost after an error, it should be state explicitly because it means that every handler has to be idempotent. If you require every handler to be idempotent, you might as well make `only_once` run again on `upgrade-charm` as said in https://github.com/juju-solutions/charms.reactive/issues/22

**Comment by stub42** [comment]
This has been touched on in https://github.com/juju-solutions/charms.reactive/issues/90, and this issue should probably be closed in favour of that one.

If we flush unitdata.kv() after each handler, then handlers will not be rerun even if a subsequent handler fails in the same hook context. However, juju will rollback any changes it made with relation-set or leader-set and the unit will end up in an inconsistent state.

**Comment by galgalesh** [comment]
+1 for closing the issue.
