### ISSUE TITLE
Broken link in the README

### ISSUE THREAD

**Issue by cmars** [juju-solutions/charms.reactive#4]
This link in README.rst is broken:
```
.. _Getting Started with Charms.Reactive: https://jujucharms.com/docs/stable/getting-started-with-charms-reactive
```

This same link is also broken on PyPI: https://pypi.python.org/pypi/charms.reactive/0.3.3

Sorry if this is the wrong place to open this bug. I didn't see a reactive document in the https://github.com/juju/docs repo.

**Comment by paulgear** [comment]
:+1: - missing the getting started link makes it pretty tricky!

**Comment by marcoceppi** [comment]
The getting started guide is currently
https://jujucharms.com/docs/devel/authors-charm-composing but that too will
be changing soon. When the new docs land in the next week I'll make sure
this gets updated

**Comment by battlemidget** [comment]
Oops, just saw this issue before creating the PR. Feel free to ignore that.

**Comment by battlemidget** [comment]
Fixed with https://github.com/juju-solutions/charms.reactive/commit/b885e4134e851fdb17ef38721e017c0cbcff8efb

**Comment by cmars** [comment]
Thanks!
