### ISSUE TITLE
charms.reactive all_states appears to be destructive

### ISSUE THREAD

**Issue by chuckbutler** [juju-solutions/charms.reactive#42]
when debugging a unit, i frequently forget that it's `charms.reactive get_states` to return the listing of active states on the unit.

when i run `charms.reactive all_states` this seems to wipe the current state of the machine, verified with charms.reactive get_states returning am empty dict

**Comment by mbruzek** [comment]
Caling  all_states getting removed. Is that what is supposed to do?

**Comment by johnsca** [comment]
I'm unable to reproduce that:

```bash
ubuntu@murdoch:~$ charms.reactive get_states
{}
ubuntu@murdoch:~$ charms.reactive set_state foo
ubuntu@murdoch:~$ charms.reactive get_states
{u'foo': None}
ubuntu@murdoch:~$ charms.reactive set_state bar
ubuntu@murdoch:~$ charms.reactive get_states
{u'foo': None, u'bar': None}
ubuntu@murdoch:~$ charms.reactive all_states
ubuntu@murdoch:~$ charms.reactive get_states
{u'foo': None, u'bar': None}
ubuntu@murdoch:~$ charms.reactive all_states foo bar && echo Yep
Yep
ubuntu@murdoch:~$ charms.reactive all_states foo bar qux && echo Yep
ubuntu@murdoch:~$ charms.reactive all_states foo bar && echo Yep
Yep
ubuntu@murdoch:~$ charms.reactive get_states
{u'foo': None, u'bar': None}
```

Can you provide more info on how to reproduce that?  That definitely should not happen!

**Comment by chuckbutler** [comment]
well, it appears this was a false positive. I'm going to close this for now pending further capacity to reproduce...
