### ISSUE TITLE
not_unless assertion improvements

### ISSUE THREAD

**Issue by stub42** [juju-solutions/charms.reactive#46]
not_unless emits warnings via juju-log if a function is called when there is unexpected state.

When running unittests the reactive state will generally not be setup at all. The spurious warnings scribble all over the output of the tests.

Also, in real deploys I'd personally much rather have not_unless fail hard than emit a warning I might not see.

We could add a function that sets a flag to change the behaviour of all the not_unless decorators, handling both of these use cases.

And while we are at it, lets add a not_if decorator to assert state is not set, to compliment not_unless asserting that state is set. I'm only able to make half of the assertions I'd like at the moment.

**Comment by johnsca** [comment]
`@not_unless` was mostly an experiment in using decorators to provide more introspectability for linting during the build process.  As far as I know, it's not heavily used in charms currently, so I think we'd be fine making it fail harder.  But regardless, we certainly should clean up the spurious logs during tests.

**Comment by stub42** [comment]
I thought initially they would be best for documentation, but was finding them helpful for guarding my normal functions. Handlers don't need them apart from documentation, since you are generally better off using a `@when` decorator instead of a `@not_unless`, but they do seem good at ensuring utility functions are only invoked by handlers when the state is acceptable ('This function will fail if the daemon is not running' style assertions).

**Comment by stub42** [comment]
Hmm... since I'm using these as assertions, maybe I should be creating assert_state_is and assert_state_isnt decorators instead and not conflating the use cases?
