### ISSUE TITLE
Bash reactive files, do not raise error when charms.reactive.sh not present

### ISSUE THREAD

**Issue by chuckbutler** [juju-solutions/charms.reactive#5]
the basic layer doesn't appear to ship charms.reactive.sh, nor does it attempt to pip install it. The example 'which charms.reactive.sh` will fail on every deploy. I propose that we embed the charms.reactive.sh in the base layer, and copy it to /usr/local/bin as the pip install would, but as part of the base layer setup.

**Comment by johnsca** [comment]
This is actually an issue with `charm generate`, as it will affect any Python library that installs a bin tool.  I think simply making a bin directory in the root charm dir should work, but it will need testing to figure out.

Regardless, this needs to be re-opened against charm-tools.

**Comment by johnsca** [comment]
Moved to charm-tools.
