### ISSUE TITLE
Conversation.set_remote should only send data if it has changed

### ISSUE THREAD

**Issue by johnsca** [juju-solutions/charms.reactive#50]
I was under the assumption that juju would intelligently handle relation-set and only trigger a hook if the data had changed.  That doesn't appear to be the case, so we should handle it in `Conversation.set_remote()` so that charm authors don't need to worry about it.

**Comment by chuckbutler** [comment]
Unless the behavior of relation-set has changed (which i assume this wraps) - it was idempotent in the past where it would not trigger a relationship-changed hook on the remote side if the data was the same. What's the behavior we're seeing here?

**Comment by johnsca** [comment]
I could have sworn I saw the relation-changed hooks getting fired repeatedly for reactive charms, but now I don't.  Perhaps this is a non-issue.

**Comment by stub42** [comment]
Its a non-issue. The only time I've seen this is when I've forgotten to maintain stable sorting of items, so the value really is changing.

**Comment by johnsca** [comment]
Ok, thanks.  I'm closing this out now.
