### ISSUE TITLE
Framework tries to run all files marked as executable and crashes on .md and .yaml files

### ISSUE THREAD

**Issue by galgalesh** [juju-solutions/charms.reactive#54]
Hi

If an interface layer or a reactive directory contains files such as README.md that are marked as executable, then you get the following error:

```
Traceback (most recent call last):
  File "hooks/install", line 19, in <module>
    main()
  File "/usr/local/lib/python3.4/dist-packages/charms/reactive/__init__.py", line 67, in main
    bus.dispatch()
  File "/usr/local/lib/python3.4/dist-packages/charms/reactive/bus.py", line 397, in dispatch
    hook_handlers = _test(Handler.get_handlers())
  File "/usr/local/lib/python3.4/dist-packages/charms/reactive/bus.py", line 381, in _test
    return list(filter(lambda h: h.test(), to_test))
  File "/usr/local/lib/python3.4/dist-packages/charms/reactive/bus.py", line 381, in <lambda>
    return list(filter(lambda h: h.test(), to_test))
  File "/usr/local/lib/python3.4/dist-packages/charms/reactive/bus.py", line 332, in test
    proc = subprocess.Popen([self._filepath, '--test'], stdout=subprocess.PIPE, env=os.environ)
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
```

I think it's logical that the framework tries to execute all files. However, I think it should show an error message that is a lot clearer. I think this is a problem that a lot of new people will run into. Marking all files as executable is something that new people often do. I don't think we should guard them from mistakes like this but the least we can do is better explain to them what is wrong. If you agree, I can create a patch that returns a clearer error message.

Kind regards
Merlijn

**Comment by galgalesh** [comment]
Maybe we can even throw a warning during build time?

**Comment by marcoceppi** [comment]
I think it's reasonable to also blacklist some extensions, like .md, from
even being considered during evaluation of files to poke. A build-time
warning may also be helpful

**Comment by galgalesh** [comment]
So, we finally found why these files were marked executable in the first place. This happened in a vagrant box. This repository was in a shared folder from a Windows host. Apparently, the permissions on a shared folder like this are interpreted as `a+rwx`. So it is very important that the reactive framework can handle this if we want to support the vagrant boxes...

**Comment by johnsca** [comment]
While I definitely agree that the error should be better, the framework should only be picking up files under the `reactive/` folder.  Why are there non-handler files in that folder?

**Comment by johnsca** [comment]
Oh, I see what the issue is.  It's picking up the copyright, README, etc, files from the interface layers.  The external handler protocol doesn't work for interface layers right now anyway, and regardless it should be explicitly whitelisted to one of `['peers.py', 'requires.py', 'provides.py']` for that directory.

**Comment by galgalesh** [comment]
Closing this since my fix is merged
