### ISSUE TITLE
Document config.* states

### ISSUE THREAD

**Issue by tvansteenburgh** [juju-solutions/charms.reactive#67]
There's nothing in the narrative docs about these. Document what states are available and when they are set.

**Comment by chuckbutler** [comment]
This is however documented in layer-basic, and the code to support these states is provided by layer-basic.

Should we potentially investigate moving them here?

**Comment by stub42** [comment]
Yes, nobody knows about the basic layer documentation or the features it provides. eg. layer options: basic: packages: is a secret
