### ISSUE TITLE
"state" is too ambiguous/overloaded, should use flag

### ISSUE THREAD

**Issue by marcoceppi** [juju-solutions/charms.reactive#76]
state, for those new to juju is confusing as it gives the impression you're impacting the Juju state when it's actually the unit state and a state that's rather shallow at the end of the day. It's also very similar to status which brings more confusion.

The suggestion was to use the word "flag" instead which doesn't have as much meaning across domains as state and can be used to better represent (and ties in nicely to @when/@when_not).

The changes would be

set_state -> set_flag
remove_state -> remove_flag

**Comment by johnsca** [comment]
@bcsaller

**Comment by johnsca** [comment]
In particular, it seems that people find `set_state` and `status_set` confusing, which is understandable, especially if they're both imported as bare identifiers.

**Comment by marcoceppi** [comment]
*updates original description*

**Comment by chuckbutler** [comment]
@johnsca when you say bare identifiers, are you referring to the following?

```python

from charms.reactive import set_state
from charmhelpers.core.hookenv import status_set

# The above make bare identifiers
```

**Comment by marcoceppi** [comment]
Yes
