### ISSUE TITLE
make use of PEX files to reduce number of files in a finished charm

### ISSUE THREAD

**Issue by battlemidget** [juju-solutions/charms.reactive#83]
Is it possible to further reduce the number of files in a reactive charm? For example, my ghost charm is 89 files with most of it being reactive deps etc.

With the use of PEX we could package each hook individually with all the requirements. This would make the charm a little bigger in size but would keep the number of files to a minimum in addition to hiding all the additional code reactive requires to run properly.

For reference here is PEX: https://github.com/pantsbuild/pex

**Comment by bcsaller** [comment]
I'd suggest that this is focusing on the wrong thing. Layers already provide a focused view of the relevant files. If the charm is thought of more as the build artifact then it can largely be ignored and the focus should be on the layer.

An argument that a smaller built artifact might aid in debugging could be made, but this would be a) debugging without understanding layers and where the charm came from (which won't help in the end) and b) PEX wouldn't help this either as I understand it.

**Comment by battlemidget** [comment]
Fair enough, however, the problem of having 89 files that make up a single charm that is exposed via jujucharms.com is still a poor user experience I would think? Most people won't know to go to github to see just the pure layer version of the charm prior to it being built.

**Comment by bcsaller** [comment]
This is true, we do however know in the built charm which layers it is built from and can teach jujucharms to inspect and show this in a more reasonable way. If reactive wasn't the standard this would be unreasonable but because it is I think it is fair to expect we can at least show a layer tab alongside the file view with links to all the source repos.

**Comment by battlemidget** [comment]
They removed the File count in jujucharms.com so at least it's a bit cleaner
